apiVersion: batch/v1
kind: Job
metadata:
  name: $JOBGROUP-$JOBNAME
  labels:
    jobgroup: $JOBGROUP
spec:
  backoffLimit: 2
  template:
    metadata:
      name: $JOBGROUP-$JOBNAME
      labels:
        jobgroup: $JOBGROUP
    spec:
      containers:
      - image: nexusjpl/ningester:$NINGESTERTAG
        name: ningester-$JOBGROUP-$JOBNAME
        args: ["$PROFILES"]
        resources:
          requests:
            cpu: "0.25"
            memory: "2Gi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
              optional: true
        volumeMounts:
        - name: data
          mountPath: /home/ningester/data/$GRANULE
          subPath: $GRANULEDATAPATH
        - name: config-volume-1
          mountPath: /home/ningester/config/$JOBCONFIGMAPNAME.yml
        - name: config-volume-2
          mountPath: /home/ningester/config/$CONNECTIONCONFIGMAPNAME.yml
      volumes:
      # this piece is replicated from job.yml so that data is mounted the same way in kubernetes
      # this need to be made in a cleaner way
      - name: data
        hostPath:
          path: /Users/loubrieu/PycharmProjects/sdap_ingest_manager/sdap_ingest_manager/collections_ingester/test/data
          type: Directory
      - name: config-volume-1
        configMap:
          name: $JOBCONFIGMAPNAME
      - name: config-volume-2
        configMap:
          name: $CONNECTIONCONFIGMAPNAME
      restartPolicy: Never
