apiVersion: batch/v1
kind: Job
metadata:
  name: collection-ingester
spec:
  template:
    spec:
      containers:
        - name: collections-ingester
          image: tloubrieu/sdap-ingest-manager:latest
          imagePullPolicy: IfNotPresent
          command: ["run_collections", "--config_path=/opt/sdap_ingester_config/"]
          volumeMounts:
            - name: config-vol
              mountPath: /opt/sdap_ingester_config/
            - name: temp-root-vol
              mountPath: /usr/local/.sdap_ingest_manager/
      volumes:
        - name: config-vol
          configMap:
            name: collection-ingester-config
        - name: temp-root-vol

      restartPolicy: Never
  backoffLimit: 4
