apiVersion: batch/v1
kind: Job
metadata:
  name: collection-ingester
spec:
  template:
    spec:
      containers:
        - name: collections-ingester
          image: tloubrieu/sdap-ingest-manager:latest
          imagePullPolicy: IfNotPresent
          command: ["run_collections", "--config=/opt/sdap_ingester_config/"]
          volumeMounts:
            - name: config-vol
              mountPath: /opt/sdap_ingester_config/
            - name: data
              mountPath: /data
      volumes:
        - name: config-vol
          configMap:
            name: collection-ingester-config
        - name: data
          hostPath:
            path: /Users/loubrieu/PycharmProjects/sdap_ingest_manager/sdap_ingest_manager/collections_ingester/test/data
            type: Directory
        - name: temp-root-vol

      restartPolicy: Never
  backoffLimit: 4
