apiVersion: batch/v1
kind: Job
metadata:
  name: collection-ingester
spec:
  template:
    spec:
      containers:
        - name: collections-ingester
          image: tloubrieu/sdap-ingest-manager:latest
          imagePullPolicy: IfNotPresent
          command: ["run_collections"]
      restartPolicy: Never
  backoffLimit: 4


