granule:
  resource: {{granule}}
slicer:
  name: sliceFileByStepSize
  dimension_step_sizes:
    time: 1
    lat: 30
    lon: 30
processors:
  - name: GridReadingProcessor
    latitude: lat
    longitude: lon
    time: time
    variable_to_read: {{variable}}
  - name: emptyTileFilter
  - name: kelvinToCelsius
  - name: tileSummary
    dataset_name: {{dataset_id}}
  - name: generateTileId

