name: PyPi publication

on:
  push:
    tags:
      - '[0-9].[0-9].*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy package
      uses: remorses/pypi@master
      with:
        setupfile: ./setup.py
        username: ${{ secrets.pypi_username }}
        password: ${{ secrets.pypi_password }}

