name: PyPi publication

on:
  tag:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy package
    uses: remorses/pypi@master
    with:
      setupfile: ./setup.py
      username: ${{ secrets.pypi_username }}
      password: ${{ secrets.pypi_password }}

